version: 2.1
jobs:
  build:
    docker:
      - image: node:12.13.0-alpine

    working_directory: ~/repo

    steps:
      - checkout

      - run:
            command: apk add docker

      - run:
          command: ls

      # BUILD APP
      - run:
          name: Install App Dependencies
          command: yarn -silent install --frozen-lockfile
          working_directory: app

      - run:
          command: yarn test
          working_directory: app

      - run:
          command: yarn build
          working_directory: app

      # BUILD API
      - run:
          name: Install API Dependencies
          command: yarn -silent install --frozen-lockfile
          working_directory: api

      - run:
          command: yarn build
          working_directory: api

      - run:
          command: cp ./package.json ./api/package.json
          working_directory: api
      - run:
          command: cp ./yarn.lock ./api/yarn.lock
          working_directory: api

      - run:
            name: Install Prod Dependencies
            command: yarn --prod -silent --frozen-lockfile
            working_directory: api/api

      - run:
          command: chmod +x ./start-servers.sh

      - setup_remote_docker

      #BUILD DOCKER IMAGE
      - run:
          name: BUILD DOCKER IMAGE
          command: docker build -t $DOCKERHUB_PROJECT:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM .

      - run:
          name: PUBLISH DOCKER IMAGE TO DOCKER HUB
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_PROJECT:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM

      #DEPLOY TO HEROKU
      - run:
          name: DEPLOY TO HEROKU
          command: |
            docker login -u $HEROKU_EMAIL -p $HEROKU_AUTH_TOKEN registry.heroku.com
            docker tag $DOCKERHUB_PROJECT:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM $HEROKU_PROJECT
            docker push $HEROKU_PROJECT
            docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP
