version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: ls

      # BUILD APP
      - run:
          name: Install App Dependencies
          command: yarn -silent install --frozen-lockfile
          working_directory: app

      - run:
          name: Lint App
          command: yarn lint
          working_directory: app

      - run:
          name: Setup Code Climate test-reporter
          command: |
             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
             chmod +x ./cc-test-reporter
             ./cc-test-reporter before-build
          working_directory: app

      - run:
          name: Test App
          command: yarn test
          working_directory: app

      - store_test_results:
          path: app/test-results

      - store_artifacts:
          path: app/test-results

      - run:
         name: Send coverage report to Code Climate
         command: ./cc-test-reporter after-build -t lcov
         working_directory: app

      - run:
          command: yarn build
          working_directory: app

      # BUILD API
      - run:
          name: Install API Dependencies
          command: yarn -silent install --frozen-lockfile
          working_directory: api

      - run:
          name: Lint API
          command: yarn lint
          working_directory: api

      - run:
          command: yarn build
          working_directory: api
