version: 2.1
jobs:
  build:
    docker:
      - image: node:12.13.0-alpine

    working_directory: ~/repo

    steps:
      - checkout

      - run:
            command: apk add docker

      - run:
          command: ls

      # BUILD APP
      - run:
          name: Install App Dependencies
          command: yarn -silent install --frozen-lockfile
          working_directory: app

      - run:
        name: Lint App
        command: yarn lint
        working_directory: app

      - run:
          name: Test App
          command: yarn test
          working_directory: app

      - run:
          command: yarn build
          working_directory: app

      # BUILD API
      - run:
          name: Install API Dependencies
          command: yarn -silent install --frozen-lockfile
          working_directory: api

      - run:
        name: Lint API
        command: yarn lint
        working_directory: api

      - run:
          command: yarn build
          working_directory: api
